apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eco-vpp.fullname" . }}-secrets
  labels: {{- include "eco-vpp.labels" . | nindent 4 }}
type: Opaque
stringData:
  ingestToken: {{ .Values.ingestToken | quote }}
  flexmeasuresToken: {{ .Values.flexmeasures.token | quote }}
  ewPrivateKey: {{ .Values.settlement.privateKey | quote }}
  gsyToken: {{ .Values.redIiAllocator.gsy.token | quote }}
